import { Anuphan } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";


const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["latin", "thai"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "อาจารย์ธฤต - Master Tharit ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className={`${anuphan.variable}  antialiased `}>
        <div className="bg-gradient-to-br from-emerald-50 via-white to-lime-50">
          <Navigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
